name: Convert CSV to JSON

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

permissions:
  contents: write   # push を許可

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests

      - name: Run converter
        run: python convert.py

      - name: Commit and push if changed
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data/coffee_shops.json
          git commit -m "Update JSON from external CSV (auto)" || echo "No changes to commit"
          git push

  notify:
    needs: build
    if: failure()   # build が失敗したときだけ実行
    runs-on: ubuntu-latest

    steps:
      - name: Send notification to Slack
        run: |
          curl -X POST -H 'Content-type: application/json' \
            --data '{"text":"CSV → JSON 更新に失敗しました"}' \
            ${{ secrets.SLACK_WEBHOOK_URL }}
